project:
  type: website
  output-dir: docs

website:
  title: "pydata"
  navbar:
    type: dark
    background: primary
    left:
      - href: README.qmd
        text: Getting started


# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

quartodoc:
  # the name used to import the package you want to create reference docs for
  package: pydata
  parser: google

  # write sidebar data to this file
  sidebar: _sidebar.yml

  sections:
    - title: "Function reference"
      contents:
        # the functions being documented in the package.
        # you can refer to anything: class methods, modules, etc..
        - ldata
        - pydata
        - rnadata